name: Clash Speedtest

on:
  schedule:
    - cron: '5 20 * * *' # 北京时间每天4点5分执行
  workflow_dispatch:

jobs:
  speedtest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install clash-speedtest
        run: go get github.com/faceair/clash-speedtest@latest

      - name: Run clash-speedtest and save output
        id: speedtest
        run: |
          clash-speedtest -c 'https://raw.githubusercontent.com/Aopex/Hub/main/Clash/%E5%96%9D%E7%B2%A5%E7%9A%84%E6%A2%AF%E5%AD%90' > speedtest_result.txt

      - name: Commit and push if changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add Clash/Speedtest
          current_time=$(date +'%Y-%m-%d')
          git commit -m "Update Clash speedtest results for $current_time"
          git push
