name: Daily Update

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  update-clash-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set date variable
        id: date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Download clash config
        run: |
          curl -o clash.yaml "https://freenode.openrunner.net/uploads/${{ env.DATE }}-clash.yaml"

      - name: Replace text
        run: |
          sed -i 's/♻️ 自动选择/♻️ 喝粥帮你选/g' clash.yaml

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.ACTIONS_DEPLOY_KEY }}@github.com/${{ github.repository }}
          mkdir -p "Clash"
          mv clash.yaml "Clash/喝粥的梯子"
          git add "Clash/喝粥的梯子"
          git commit -m "Update clash config with today's date"
