name: Clash Speedtest

on:
  schedule:
    - cron: '5 20 * * *'
  workflow_dispatch:

jobs:
  speedtest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        node-version: '20'

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Clone clash-speedtest repository
      run: git clone https://github.com/faceair/clash-speedtest.git

    - name: Install clash-speedtest
      run: cd clash-speedtest && go install

    - name: Run clash-speedtest
      run: clash-speedtest -c 'https://raw.githubusercontent.com/Aopex/Hub/main/Clash/%E5%96%9D%E7%B2%A5%E7%9A%84%E6%A2%AF%E5%AD%90' -concurrent 8 -output yaml -size 52428800 > Clash/Speedtest

    - name: Commit results
      run: |
        mkdir -p Clash
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add Clash/Speedtest
        git commit -m "Update speedtest results $(date +'%Y-%m-%d')"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
